export const ASYNC_STORAGE_KEY = {
    IS_FIRST_TIME: 'IS_FIRST_TIME',
    APPLE_FAMILY_NAME: 'APPLE_FAMILY_NAME',
    APPLE_GIVEN_NAME: 'APPLE_GIVEN_NAME',
    APPLE_MIDDLE_NAME: 'APPLE_MIDDLE_NAME',
    APPLE_EMAIL: 'APPLE_EMAIL',
    USER_TYPE: 'USER_TYPE',
    USER_ID: 'USER_ID',
    ACCESS_TOKEN: 'ACCESS_TOKEN'
};

export const USER_TYPE = {
    KAKAO: 'KAKAO',
    FACEBOOK: 'FACEBOOK',
    GOOGLE: 'GOOGLE',
    SKT: 'SKT'
}

export const WEBVIEW_EVENT_TYPE = {
    LOGGED_IN: 'LOGGED_IN',
    OPEN_MENU: 'OPEN_MENU',
    ALARM_CLICKED: 'ALARM_CLICKED',
    URL_CHANGED: 'URL_CHANGED',
    HOME_CLICKED: 'HOME_CLICKED',
    CLOSE_MODAL: 'CLOSE_MODAL',
    SHARE_LINK: 'SHARE_LINK'
};


export const ENV = {
    DEV: 'DEV',
    PROD: 'PROD'
};

export const COMMON_CODE = {
    SUCCESS: "0000",
    FAIL: "0001",
};

export const ErrorMessage = {
    NOT_FOUND_USER: 'NOT_FOUND_USER',
    SNS_USER: 'SNS_USER',
    EXIST: 'EXIST',
    ACCESS_DENIED: 'ACCESS_DENIED',
    WRONG_PASSWORD: 'WRONG_PASSWORD',
    NETWORK_ERROR: 'Network Error',
    BLOCKED_USER: 'BLOCKED_USER',
    INVALID_ACCESS: 'INVALID_ACCESS'
};

export const PORTAL = {
    KAKAO: 'KAKAO',
    GOOGLE: 'GOOGLE',
    APPLE: 'APPLE',
    TID: 'TID'
}
